language: node_js
node_js:
  - "4.4.2"

env:
  - SERVE_STATIC=true

services:
  - redis-server

cache:
  directories:
    - node_modules

script: "npm run test:ci && npm run sass; NODE_ENV='ci' npm start& npm run test:acceptance"
