
nginx:
    build: "./docker/nginx/"
    volumes:
        - "./public:/public:z"
    links:
        - app:app
    ports:
        - "80:80"
app:
    build: .
    ports:
        - "8080"
    volumes:
        - ".:/app:z"
    links:
        - redis
    environment:
        - NODE_ENV=development
redis:
    image: redis
    ports:
        - "6379"
