nginx:
    build: "./docker/nginx/"
    volumes:
        - "./public:/public:z"
    links:
        - app1:app1
        - app2:app2
        - app3:app3
    ports:
        - "80:80"
        - "443:443"
    environment:
        - DOCKER_COMPOSE=1
app1:
    build: .
    ports:
        - "8080"
    volumes:
        - ".:/srv/app:z"
    links:
        - redis
    environment:
        - DOCKER_COMPOSE=1
app2:
    build: .
    ports:
        - "8080"
    volumes:
        - ".:/srv/app:z"
    links:
        - redis
    environment:
        - DOCKER_COMPOSE=1
app3:
    build: .
    ports:
        - "8080"
    volumes:
        - ".:/srv/app:z"
    links:
        - redis
    environment:
        - DOCKER_COMPOSE=1
redis:
    image: redis
    ports:
        - "6379"
